server:
  address:     ":8000"
  openapiPath: "/api.json"
  swaggerPath: "/swagger"
  dataPath: "/var/lib/skylight"

logger:
  level : "all"
  stdout: true

session:
  type: "file"
  path: "/var/lib/skylight/gsessions"

database:
  link:  "sqlite::@file(/var/lib/skylight/skylight.db)"
