server:
  address:     ":8000"
  openapiPath: "/api.json"
  swaggerPath: "/swagger"
  dataPath: "/var/lib/skylight"

logger:
  level : "all"
  stdout: true

session:
  type: "file"
  path: "/var/lib/skylight/gsessions"

database:
  type:  "sqlite"
  link:  "/var/lib/skylight/skylight.db"
