server:
  address:     ":8081"
  openapiPath: "/api.json"
  swaggerPath: "/swagger"
  dataPath: "/var/lib/skylight"

logger:
  level : "info"
  stdout: true

session:
  default:
    type: "file"
    path: "/var/lib/skylight/gsessions"

database:
  debug: true
  link:  "sqlite::@file(/var/lib/skylight/skylight.db)"
